#!/usr/bin/env python3
"""
Generate _data/content-plan.csv — 50 planned topics per doctor, starting tomorrow.
Run once: python scripts/generate-content-plan.py
Re-run to extend or reset (existing 'published' rows are preserved).
"""
import csv, os
from datetime import date, timedelta

REPO     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT      = os.path.join(REPO, "_data", "content-plan.csv")
FIELDNAMES = ["doctor_folder","planned_date","topic_en","slug_hint","status","built_slug","built_url","built_at"]

START = date.today() + timedelta(days=1)   # tomorrow

# 50 topics per doctor — (topic_en, slug_hint)
PLAN = {

"dr-owais": [
    ("Nausea and vomiting after chemotherapy",       "nausea-vomiting-chemotherapy"),
    ("Hair loss during cancer treatment",            "hair-loss-cancer-treatment"),
    ("Cancer-related fatigue management",            "cancer-fatigue-management"),
    ("Nutrition and diet during cancer treatment",   "cancer-nutrition-diet"),
    ("Breast cancer treatment options",              "breast-cancer-treatment"),
    ("Cervical cancer symptoms and treatment",       "cervical-cancer-treatment"),
    ("Ovarian cancer signs and diagnosis",           "ovarian-cancer-diagnosis"),
    ("Colorectal cancer screening",                  "colorectal-cancer-screening"),
    ("What is lymphoma",                             "what-is-lymphoma"),
    ("Types of leukemia",                            "types-of-leukemia"),
    ("Multiple myeloma treatment",                   "multiple-myeloma-treatment"),
    ("Blood tests used in cancer diagnosis",         "blood-tests-cancer-diagnosis"),
    ("PET-CT scan explained for patients",           "pet-ct-scan-explained"),
    ("Palliative care in cancer",                    "palliative-care-cancer"),
    ("Genetic testing for cancer risk",              "genetic-testing-cancer-risk"),
    ("Hereditary cancer syndromes",                  "hereditary-cancer-syndromes"),
    ("Managing cancer recurrence",                   "managing-cancer-recurrence"),
    ("Immunotherapy side effects",                   "immunotherapy-side-effects"),
    ("Targeted therapy explained",                   "targeted-therapy-explained"),
    ("Oral chemotherapy medications",                "oral-chemotherapy-medications"),
    ("Chemotherapy port explained",                  "chemotherapy-port-explained"),
    ("Cancer clinical trials in India",              "cancer-clinical-trials-india"),
    ("Questions to ask your oncologist",             "questions-to-ask-oncologist"),
    ("Cancer survivorship care",                     "cancer-survivorship-care"),
    ("Fertility preservation before chemotherapy",   "fertility-preservation-chemotherapy"),
    ("Mouth sores during chemotherapy",              "mouth-sores-chemotherapy"),
    ("Neuropathy from chemotherapy",                 "chemotherapy-neuropathy"),
    ("Cancer and diabetes management",               "cancer-diabetes-management"),
    ("Blood transfusion in cancer treatment",        "blood-transfusion-cancer"),
    ("Anti-nausea medications for chemotherapy",     "anti-nausea-medications-chemotherapy"),
    ("Cancer diagnosis process step by step",        "cancer-diagnosis-process"),
    ("Reading your pathology report",                "reading-pathology-report"),
    ("Cancer prognosis what it means",               "cancer-prognosis-explained"),
    ("Anaemia during cancer treatment",              "cancer-related-anaemia"),
    ("Skin changes during chemotherapy",             "skin-changes-chemotherapy"),
    ("Cancer treatment during pregnancy",            "cancer-treatment-pregnancy"),
    ("Triple negative breast cancer",                "triple-negative-breast-cancer"),
    ("HER2 positive breast cancer",                  "her2-positive-breast-cancer"),
    ("Stomach cancer symptoms",                      "stomach-cancer-symptoms"),
    ("Kidney cancer treatment options",              "kidney-cancer-treatment"),
    ("Bladder cancer diagnosis",                     "bladder-cancer-diagnosis"),
    ("Thyroid cancer types and treatment",           "thyroid-cancer-treatment"),
    ("Prostate cancer treatment options",            "prostate-cancer-treatment"),
    ("Esophageal cancer symptoms",                   "esophageal-cancer-symptoms"),
    ("Cervical cancer prevention and HPV vaccine",   "cervical-cancer-hpv-vaccine"),
    ("Cancer screening guidelines India",            "cancer-screening-india"),
    ("Why cancer second opinion matters",            "why-cancer-second-opinion"),
    ("Preparing for your first chemotherapy session","preparing-for-chemotherapy"),
    ("Cancer caregiver guide",                       "cancer-caregiver-guide"),
    ("Cancer pain relief options",                   "cancer-pain-relief"),
],

"dr-vinay": [
    ("Types of cancer surgery",                      "types-cancer-surgery"),
    ("Laparoscopic cancer surgery explained",        "laparoscopic-cancer-surgery"),
    ("Breast conservation surgery lumpectomy",       "lumpectomy-breast-surgery"),
    ("Mastectomy types and recovery",                "mastectomy-types-recovery"),
    ("Sentinel lymph node biopsy",                   "sentinel-lymph-node-biopsy"),
    ("Thyroid cancer surgery",                       "thyroid-surgery-cancer"),
    ("Colorectal cancer surgery",                    "colorectal-surgery"),
    ("Colostomy explained for patients",             "colostomy-explained"),
    ("Ileostomy care and management",                "ileostomy-care"),
    ("Liver resection surgery",                      "liver-resection-surgery"),
    ("Splenectomy for cancer",                       "splenectomy-cancer"),
    ("Kidney nephrectomy surgery",                   "nephrectomy-surgery"),
    ("Ovarian cancer debulking surgery",             "ovarian-debulking-surgery"),
    ("Cancer surgery wound care",                    "cancer-surgery-wound-care"),
    ("Post-surgery pain management",                 "post-surgery-pain-management"),
    ("Recovery after cancer surgery",                "cancer-surgery-recovery"),
    ("Cancer surgery complications",                 "cancer-surgery-complications"),
    ("DVT prevention after cancer surgery",          "dvt-prevention-after-surgery"),
    ("Pre-surgery preparation for cancer",           "pre-surgery-preparation"),
    ("Nutrition before cancer surgery",              "nutrition-before-cancer-surgery"),
    ("Cancer surgery anaesthesia",                   "cancer-surgery-anaesthesia"),
    ("Surgical staging of cancer",                   "surgical-staging-cancer"),
    ("Curative vs palliative surgery",               "curative-vs-palliative-surgery"),
    ("Breast reconstruction after mastectomy",       "breast-reconstruction-after-mastectomy"),
    ("Port insertion for chemotherapy",              "port-insertion-surgery"),
    ("Thoracoscopy VATS cancer surgery",             "vats-thoracoscopy"),
    ("Esophagectomy for esophageal cancer",          "esophagectomy-surgery"),
    ("Gastrectomy types for stomach cancer",         "gastrectomy-types"),
    ("Pancreatectomy procedure",                     "pancreatectomy-procedure"),
    ("Whipple surgery recovery",                     "whipple-surgery-recovery"),
    ("Hernia after cancer surgery",                  "hernia-after-cancer-surgery"),
    ("Scar management after cancer surgery",         "scar-management-cancer-surgery"),
    ("Cancer surgery in elderly patients",           "cancer-surgery-elderly"),
    ("Cancer surgery cost Hyderabad",                "cancer-surgery-cost-hyderabad"),
    ("Questions before cancer surgery",              "cancer-surgery-questions"),
    ("Life after cancer surgery",                    "life-after-cancer-surgery"),
    ("Robotic cancer surgery India",                 "robotic-cancer-surgery-india"),
    ("Abdominal cancer surgery recovery",            "abdominal-cancer-surgery-recovery"),
    ("Rectal cancer surgery options",                "rectal-cancer-surgery"),
    ("Parathyroid surgery for cancer",               "parathyroid-surgery"),
    ("Adrenalectomy procedure",                      "adrenalectomy-procedure"),
    ("Pelvic exenteration surgery",                  "pelvic-exenteration-surgery"),
    ("Surgical removal of lymph nodes",              "lymph-node-removal-surgery"),
    ("Cancer biopsy types explained",                "cancer-biopsy-types"),
    ("Intraoperative frozen section",                "intraoperative-frozen-section"),
    ("R0 R1 R2 resection margins",                   "cancer-resection-margins"),
    ("Cancer surgery second opinion",                "cancer-surgery-second-opinion"),
    ("Day surgery cancer procedures",                "day-surgery-cancer"),
    ("Reconstructive flap surgery cancer",           "reconstructive-flap-surgery"),
    ("Preparing questions for your surgeon",         "questions-for-cancer-surgeon"),
],

"dr-murali": [
    ("Melanoma surgery and margins",                 "melanoma-surgery"),
    ("Skin cancer surgery types",                    "skin-cancer-surgery"),
    ("Retroperitoneal sarcoma surgery",              "retroperitoneal-sarcoma-surgery"),
    ("Leiomyosarcoma treatment",                     "leiomyosarcoma-treatment"),
    ("Liposarcoma surgery",                          "liposarcoma-surgery"),
    ("Limb-sparing surgery for bone cancer",         "limb-sparing-surgery"),
    ("Osteosarcoma limb salvage",                    "osteosarcoma-limb-salvage"),
    ("Rectal cancer sphincter preservation",         "rectal-sphincter-preservation"),
    ("Low anterior resection surgery",               "low-anterior-resection"),
    ("Sigmoid colon cancer surgery",                 "sigmoid-colon-cancer-surgery"),
    ("Laparoscopic bowel resection",                 "laparoscopic-bowel-resection"),
    ("Hemorrhoids vs rectal cancer",                 "hemorrhoids-vs-rectal-cancer"),
    ("Liver metastases surgery",                     "liver-metastases-surgery"),
    ("Thermal ablation liver tumours",               "thermal-ablation-liver-tumours"),
    ("Bile duct repair surgery",                     "bile-duct-repair-surgery"),
    ("Cholecystectomy for gallbladder cancer",       "cholecystectomy-gallbladder-cancer"),
    ("Total gastrectomy recovery",                   "total-gastrectomy-recovery"),
    ("Small bowel resection surgery",                "small-bowel-resection"),
    ("Peritoneal wash cytology",                     "peritoneal-wash-cytology"),
    ("Second-look surgery ovarian cancer",           "second-look-surgery-ovarian"),
    ("Interval debulking surgery",                   "interval-debulking-surgery"),
    ("Cancer surgery in patients with diabetes",     "cancer-surgery-diabetes"),
    ("Anastomosis leak prevention after bowel surgery","anastomosis-leak-prevention"),
    ("Ewing sarcoma treatment",                      "ewing-sarcoma-treatment"),
    ("Synovial sarcoma treatment",                   "synovial-sarcoma-treatment"),
    ("Amputation for bone cancer",                   "amputation-bone-cancer"),
    ("Right hemicolectomy surgery",                  "right-hemicolectomy"),
    ("Left hemicolectomy surgery",                   "left-hemicolectomy"),
    ("D2 lymphadenectomy gastric cancer",            "d2-lymphadenectomy-gastric"),
    ("Portal vein embolization surgery",             "portal-vein-embolization"),
    ("Distal pancreatectomy procedure",              "distal-pancreatectomy"),
    ("Gallbladder cancer radical cholecystectomy",   "radical-cholecystectomy-gallbladder"),
    ("GIST gastrointestinal stromal tumour",         "gist-tumour-treatment"),
    ("Mesenteric tumour resection",                  "mesenteric-tumour-resection"),
    ("Colon cancer with peritoneal spread",          "colon-cancer-peritoneal-spread"),
    ("Uterine cancer surgery",                       "uterine-cancer-surgery"),
    ("Malignant ascites management",                 "malignant-ascites-management"),
    ("Laparoscopic staging peritoneal cancer",       "laparoscopic-staging-peritoneal"),
    ("Transverse colon cancer surgery",              "transverse-colon-cancer"),
    ("Anorectal cancer surgery",                     "anorectal-cancer-surgery"),
    ("Diverticulitis vs colon cancer",               "diverticulitis-vs-colon-cancer"),
    ("Phantom limb pain management",                 "phantom-limb-pain-management"),
    ("Intraoperative bleeding management",           "intraoperative-bleeding-management"),
    ("Liver cancer thermal microwave ablation",      "microwave-ablation-liver"),
    ("Proximal gastrectomy stomach cancer",          "proximal-gastrectomy"),
    ("Pancreatic resection recovery",                "pancreatic-resection-recovery"),
    ("Abdominoperineal resection APR",               "abdominoperineal-resection"),
    ("Stoma reversal after bowel surgery",           "stoma-reversal-surgery"),
    ("Enhanced recovery after surgery ERAS",         "eras-protocol-cancer-surgery"),
    ("Cancer surgery blood loss management",         "cancer-surgery-blood-loss"),
],

"dr-sandeep": [
    ("Oral cancer surgery treatment",               "oral-cancer-surgery"),
    ("Tongue cancer treatment",                     "tongue-cancer-treatment"),
    ("Lip cancer surgery",                          "lip-cancer-surgery"),
    ("Buccal mucosa cheek cancer",                  "buccal-mucosa-cancer"),
    ("Floor of mouth cancer",                       "floor-of-mouth-cancer"),
    ("Laryngeal cancer voice box",                  "laryngeal-cancer-treatment"),
    ("Total laryngectomy voice rehabilitation",     "laryngectomy-voice-rehab"),
    ("Hypopharyngeal cancer",                       "hypopharyngeal-cancer"),
    ("Oropharyngeal cancer HPV related",            "oropharyngeal-cancer-hpv"),
    ("Tonsil cancer treatment",                     "tonsil-cancer-treatment"),
    ("Nasopharyngeal cancer",                       "nasopharyngeal-cancer"),
    ("Nasal cavity cancer",                         "nasal-cavity-cancer"),
    ("Salivary gland cancer types",                 "salivary-gland-cancer"),
    ("Parotid gland tumour surgery",                "parotid-gland-surgery"),
    ("Neck dissection types",                       "neck-dissection-types"),
    ("Modified radical neck dissection",            "modified-radical-neck-dissection"),
    ("Total thyroidectomy surgery",                 "total-thyroidectomy"),
    ("Papillary thyroid cancer treatment",          "papillary-thyroid-cancer"),
    ("Follicular thyroid cancer",                   "follicular-thyroid-cancer"),
    ("Medullary thyroid cancer",                    "medullary-thyroid-cancer"),
    ("Thyroid cancer recurrence",                   "thyroid-cancer-recurrence"),
    ("Skull base tumour surgery",                   "skull-base-tumour-surgery"),
    ("Carotid body tumour paraganglioma",           "paraganglioma-treatment"),
    ("Adenoid cystic carcinoma",                    "adenoid-cystic-carcinoma"),
    ("Mucoepidermoid carcinoma",                    "mucoepidermoid-carcinoma"),
    ("Head neck cancer trismus jaw",                "head-neck-cancer-trismus"),
    ("Dry mouth xerostomia after head neck cancer", "xerostomia-cancer-treatment"),
    ("Swallowing difficulty after head neck cancer","dysphagia-head-neck-cancer"),
    ("Head neck cancer rehabilitation",             "head-neck-cancer-rehabilitation"),
    ("Speech therapy after laryngectomy",           "speech-therapy-laryngectomy"),
    ("Neck lump when to worry",                     "neck-lump-causes"),
    ("Hoarseness persistent causes cancer",         "hoarseness-cancer-signs"),
    ("Non-healing mouth ulcer and cancer",          "mouth-ulcer-cancer-warning"),
    ("Leukoplakia oral cancer risk",                "leukoplakia-oral-cancer"),
    ("Submucous fibrosis and cancer",               "submucous-fibrosis-cancer"),
    ("Tobacco gutka and oral cancer",               "tobacco-oral-cancer"),
    ("Base of tongue cancer",                       "base-of-tongue-cancer"),
    ("Partial laryngectomy voice preservation",     "partial-laryngectomy"),
    ("Palate cancer surgery",                       "palate-cancer-surgery"),
    ("Jaw mandibular cancer surgery",               "jaw-cancer-surgery"),
    ("Paranasal sinus cancer",                      "paranasal-sinus-cancer"),
    ("Anaplastic thyroid cancer",                   "anaplastic-thyroid-cancer"),
    ("Head neck cancer Hyderabad treatment",        "head-neck-cancer-hyderabad"),
    ("Swallowing therapy after head neck cancer",   "swallowing-therapy-cancer"),
    ("Radiation after head neck surgery",           "radiation-head-neck-surgery"),
    ("Chemotherapy for head neck cancer",           "chemotherapy-head-neck-cancer"),
    ("Head neck cancer nutrition support",          "head-neck-cancer-nutrition"),
    ("Tracheostomy care after head neck surgery",   "tracheostomy-care-cancer"),
    ("Reconstructive surgery after head neck cancer","reconstruction-head-neck-cancer"),
    ("Questions to ask head neck cancer surgeon",   "head-neck-cancer-surgeon-questions"),
],

"dr-kiranmayee": [
    ("Understanding cancer immunotherapy",           "understanding-immunotherapy"),
    ("Lung cancer types and stages",                "lung-cancer-types-stages"),
    ("Breast cancer hormone receptor positive",     "hormone-receptor-breast-cancer"),
    ("Non-Hodgkin lymphoma treatment",              "non-hodgkin-lymphoma"),
    ("Chronic myeloid leukemia CML",                "chronic-myeloid-leukemia"),
    ("Melanoma treatment options",                  "melanoma-treatment"),
    ("Pancreatic cancer early signs",               "pancreatic-cancer-signs"),
    ("Liver cancer treatment Hyderabad",            "liver-cancer-treatment-hyderabad"),
    ("Endometrial uterine cancer treatment",        "uterine-cancer-treatment"),
    ("Bone cancer types and treatment",             "bone-cancer-types"),
    ("Soft tissue sarcoma treatment",               "soft-tissue-sarcoma"),
    ("Neuroendocrine tumours NET",                  "neuroendocrine-tumours"),
    ("Cholangiocarcinoma bile duct cancer",         "bile-duct-cancer"),
    ("Cancer and blood clots DVT",                  "cancer-blood-clots-dvt"),
    ("Immunotherapy checkpoint inhibitors",         "checkpoint-inhibitors-immunotherapy"),
    ("CAR T-cell therapy explained",                "car-t-cell-therapy"),
    ("PARP inhibitors ovarian cancer",              "parp-inhibitors-cancer"),
    ("CDK inhibitors breast cancer",                "cdk-inhibitors-breast-cancer"),
    ("Combination chemotherapy regimens",           "combination-chemotherapy"),
    ("Managing weight during chemotherapy",         "weight-management-chemotherapy"),
    ("Cancer and mental health",                    "cancer-mental-health"),
    ("Exercise during cancer treatment",            "exercise-during-cancer"),
    ("Cancer pain types and management",            "cancer-pain-types"),
    ("Cancer end of life care",                     "cancer-end-of-life-care"),
    ("Cancer rehabilitation after treatment",       "cancer-rehabilitation"),
    ("Return to work after cancer",                 "return-to-work-cancer"),
    ("Cancer insurance India guide",                "cancer-insurance-india"),
    ("Government cancer schemes India",             "government-cancer-schemes-india"),
    ("Telemedicine for cancer follow-up",           "telemedicine-cancer-followup"),
    ("Cancer in young adults",                      "cancer-young-adults"),
    ("Antibody drug conjugates cancer",             "antibody-drug-conjugates"),
    ("Maintenance therapy in cancer",               "maintenance-therapy-cancer"),
    ("Adjuvant vs neoadjuvant therapy",             "adjuvant-neoadjuvant-therapy"),
    ("Dose dense chemotherapy explained",           "dose-dense-chemotherapy"),
    ("Growth factors in chemotherapy",              "growth-factors-chemotherapy"),
    ("Febrile neutropenia management",              "febrile-neutropenia"),
    ("Cancer and heart disease cardio-oncology",    "cardio-oncology-cancer"),
    ("Second primary cancer risk",                  "second-primary-cancer"),
    ("Cancer treatment at home tips",               "cancer-treatment-at-home"),
    ("Oral cancer prevention",                      "oral-cancer-prevention"),
    ("Colon cancer prevention",                     "colon-cancer-prevention"),
    ("Pancreatic cancer warning signs",             "pancreatic-cancer-warning-signs"),
    ("Vulvar cancer treatment",                     "vulvar-cancer-treatment"),
    ("Penile cancer treatment",                     "penile-cancer-treatment"),
    ("Anal cancer treatment",                       "anal-cancer-treatment"),
    ("Adrenal cancer treatment",                    "adrenal-cancer-treatment"),
    ("Cancer genetic counselling",                  "cancer-genetic-counselling"),
    ("Complementary medicine and cancer",           "complementary-medicine-cancer"),
    ("Hospice care for cancer patients",            "hospice-care-cancer"),
    ("Cancer caregiver burnout",                    "cancer-caregiver-burnout"),
],

"dr-basudev": [
    ("Bone marrow transplant explained",            "bone-marrow-transplant-explained"),
    ("Autologous bone marrow transplant",           "autologous-bmt"),
    ("Allogeneic bone marrow transplant",           "allogeneic-bmt"),
    ("Stem cell donation process",                  "stem-cell-donation"),
    ("Bone marrow donor compatibility HLA",         "bone-marrow-donor-compatibility"),
    ("BMT recovery timeline",                       "bmt-recovery-timeline"),
    ("Graft versus host disease GVHD",              "graft-versus-host-disease"),
    ("Chronic GVHD management",                     "chronic-gvhd-management"),
    ("What is leukemia",                            "what-is-leukemia"),
    ("Acute myeloid leukemia AML",                  "acute-myeloid-leukemia"),
    ("Acute lymphoblastic leukemia ALL",            "acute-lymphoblastic-leukemia"),
    ("Chronic lymphocytic leukemia CLL",            "chronic-lymphocytic-leukemia"),
    ("Hairy cell leukemia",                         "hairy-cell-leukemia"),
    ("Myelodysplastic syndrome MDS",                "myelodysplastic-syndrome"),
    ("Myelofibrosis treatment",                     "myelofibrosis-treatment"),
    ("Polycythemia vera management",                "polycythemia-vera"),
    ("Essential thrombocythemia",                   "essential-thrombocythemia"),
    ("Aplastic anemia treatment",                   "aplastic-anemia-treatment"),
    ("Thalassemia and stem cell therapy",           "thalassemia-stem-cell-therapy"),
    ("Hodgkin lymphoma treatment",                  "hodgkin-lymphoma-treatment"),
    ("Diffuse large B-cell lymphoma DLBCL",         "diffuse-large-b-cell-lymphoma"),
    ("Follicular lymphoma treatment",               "follicular-lymphoma"),
    ("Mantle cell lymphoma",                        "mantle-cell-lymphoma"),
    ("Burkitt lymphoma",                            "burkitt-lymphoma"),
    ("T-cell lymphoma treatment",                   "t-cell-lymphoma"),
    ("Waldenstrom macroglobulinemia",               "waldenstrom-macroglobulinemia"),
    ("Multiple myeloma bone pain",                  "multiple-myeloma-bone-pain"),
    ("Smoldering myeloma monitoring",               "smoldering-myeloma"),
    ("Bortezomib for myeloma",                      "bortezomib-myeloma"),
    ("Daratumumab myeloma treatment",               "daratumumab-myeloma"),
    ("Venetoclax in blood cancers",                 "venetoclax-blood-cancer"),
    ("Ibrutinib CLL treatment",                     "ibrutinib-cll"),
    ("Rituximab lymphoma treatment",                "rituximab-lymphoma"),
    ("Bone marrow biopsy procedure",                "bone-marrow-biopsy-procedure"),
    ("Complete blood count CBC interpretation",     "cbc-cancer-interpretation"),
    ("Flow cytometry blood cancer",                 "flow-cytometry-cancer"),
    ("FISH testing blood cancer",                   "fish-testing-blood-cancer"),
    ("Blood cancer treatment Hyderabad",            "blood-cancer-treatment-hyderabad"),
    ("BMT cost India",                              "bmt-cost-india"),
    ("Life after bone marrow transplant",           "life-after-bmt"),
    ("Infections after BMT",                        "infections-after-bmt"),
    ("Engraftment syndrome after BMT",              "engraftment-syndrome"),
    ("Peripheral blood stem cell harvest",          "peripheral-blood-stem-cell-harvest"),
    ("Cord blood transplant",                       "cord-blood-transplant"),
    ("Haploidentical transplant",                   "haploidentical-transplant"),
    ("Reduced intensity conditioning BMT",          "reduced-intensity-conditioning-bmt"),
    ("NK cell lymphoma treatment",                  "nk-cell-lymphoma"),
    ("Amyloidosis and blood cancer",                "amyloidosis-blood-cancer"),
    ("Bone marrow failure syndromes",               "bone-marrow-failure-syndromes"),
    ("Blood cancer diet and nutrition",             "blood-cancer-diet-nutrition"),
],

"dr-raghvendra": [
    ("What is radiation therapy",                   "what-is-radiation-therapy"),
    ("External beam radiation therapy",             "external-beam-radiation"),
    ("IMRT intensity modulated radiation",          "imrt-radiation-therapy"),
    ("IGRT image guided radiation therapy",         "igrt-radiation-therapy"),
    ("Stereotactic radiosurgery SRS",               "stereotactic-radiosurgery"),
    ("SBRT stereotactic body radiation",            "sbrt-radiation-therapy"),
    ("Brachytherapy internal radiation explained",  "brachytherapy-explained"),
    ("High dose rate brachytherapy",                "high-dose-rate-brachytherapy"),
    ("Radiation therapy for breast cancer",         "breast-cancer-radiation"),
    ("Radiation therapy for cervical cancer",       "cervical-cancer-radiation"),
    ("Radiation therapy for prostate cancer",       "prostate-cancer-radiation"),
    ("Radiation therapy for lung cancer",           "lung-cancer-radiation"),
    ("Radiation therapy for head neck cancer",      "head-neck-radiation-therapy"),
    ("Radiation therapy for rectal cancer",         "rectal-cancer-radiation"),
    ("Whole brain radiation therapy",               "whole-brain-radiation"),
    ("Palliative radiation for bone pain",          "palliative-radiation-bone-pain"),
    ("Radiation therapy side effects",              "radiation-therapy-side-effects"),
    ("Skin reactions during radiation therapy",     "skin-reactions-radiation"),
    ("Fatigue during radiation therapy",            "fatigue-radiation-therapy"),
    ("Radiation mucositis treatment",               "radiation-mucositis"),
    ("Radiation enteritis bowel side effects",      "radiation-enteritis"),
    ("Radiation cystitis bladder effects",          "radiation-cystitis"),
    ("Radiation therapy simulation process",        "radiation-therapy-simulation"),
    ("Treatment planning for radiation therapy",    "radiation-treatment-planning"),
    ("How many radiation sessions needed",          "radiation-therapy-fractions"),
    ("Hypofractionated radiation therapy",          "hypofractionated-radiation"),
    ("Concurrent chemoradiation",                   "concurrent-chemoradiation"),
    ("Radiation for brain metastases",              "radiation-brain-metastases"),
    ("Spinal cord compression radiation",           "spinal-cord-compression-radiation"),
    ("Radiation for liver tumours SABR",            "sabr-liver-tumours"),
    ("Radioiodine therapy thyroid cancer",          "radioiodine-therapy-thyroid"),
    ("PRRT for neuroendocrine tumours",             "prrt-neuroendocrine-tumours"),
    ("Lutetium DOTATATE therapy",                   "lutetium-dotatate-therapy"),
    ("Y90 radioembolization liver cancer",          "y90-radioembolization"),
    ("Radiation therapy vs surgery choice",         "radiation-vs-surgery"),
    ("Proton therapy vs conventional radiation",    "proton-therapy-vs-radiation"),
    ("Radiation therapy quality of life",           "radiation-quality-of-life"),
    ("Radiation therapy myths India",               "radiation-therapy-myths"),
    ("Radiation therapy cost Hyderabad",            "radiation-therapy-cost-hyderabad"),
    ("Radiation therapy safety questions",          "radiation-therapy-safety"),
    ("Re-irradiation for recurrent cancer",         "re-irradiation-cancer"),
    ("Second cancer risk after radiation",          "second-cancer-after-radiation"),
    ("Radiation protection for family members",     "radiation-protection-family"),
    ("Radiation therapy and fertility",             "radiation-therapy-fertility"),
    ("Accelerated partial breast irradiation",      "accelerated-partial-breast-irradiation"),
    ("Intraoperative radiation therapy IORT",       "intraoperative-radiation-therapy"),
    ("Total body irradiation TBI",                  "total-body-irradiation"),
    ("Radiofrequency ablation RFA cancer",          "radiofrequency-ablation-cancer"),
    ("TACE transarterial chemoembolization",        "tace-liver-cancer"),
    ("Radiation therapy for esophageal cancer",     "esophageal-cancer-radiation"),
],

"dr-craghavendra": [
    ("Colon cancer treatment options",              "colon-cancer-treatment"),
    ("Rectal cancer treatment",                     "rectal-cancer-treatment"),
    ("Appendix cancer and pseudomyxoma peritonei",  "appendix-cancer-treatment"),
    ("Peritoneal carcinomatosis",                   "peritoneal-carcinomatosis"),
    ("CEA tumor marker explained",                  "cea-tumor-marker"),
    ("CA 125 test ovarian cancer",                  "ca125-test-explained"),
    ("CA 19-9 test pancreatic cancer",              "ca19-9-test-explained"),
    ("AFP test liver cancer",                       "afp-test-liver-cancer"),
    ("PSA test prostate cancer",                    "psa-test-explained"),
    ("Core needle biopsy procedure",                "core-needle-biopsy"),
    ("Liquid biopsy cancer detection",              "liquid-biopsy-cancer"),
    ("Next generation sequencing cancer",           "next-generation-sequencing-cancer"),
    ("Microsatellite instability MSI",              "microsatellite-instability"),
    ("KRAS mutation colorectal cancer",             "kras-mutation-colorectal"),
    ("EGFR mutation lung cancer",                   "egfr-mutation-lung-cancer"),
    ("BRAF mutation cancer treatment",              "braf-mutation-cancer"),
    ("PDL1 expression immunotherapy",               "pdl1-expression-cancer"),
    ("Precision oncology Hyderabad",                "precision-oncology-hyderabad"),
    ("Cancer diet myths",                           "cancer-diet-myths"),
    ("Sugar and cancer link",                       "sugar-cancer-link"),
    ("Alcohol and cancer risk",                     "alcohol-cancer-risk"),
    ("Obesity and cancer risk",                     "obesity-cancer-risk"),
    ("Cancer prevention strategies",                "cancer-prevention-strategies"),
    ("Cancer early detection India",                "cancer-early-detection-india"),
    ("Colonoscopy cancer screening",                "colonoscopy-screening"),
    ("Mammography breast screening",                "mammography-screening"),
    ("Pap smear cervical screening",                "pap-smear-screening"),
    ("Response evaluation RECIST criteria",         "recist-criteria-cancer"),
    ("Adjuvant chemotherapy explained",             "adjuvant-chemotherapy-explained"),
    ("Bone marrow suppression chemotherapy",        "bone-marrow-suppression"),
    ("Cancer biomarkers explained",                 "cancer-biomarkers-explained"),
    ("Biliary tract cancer treatment",              "biliary-tract-cancer"),
    ("Duodenal cancer",                             "duodenal-cancer-treatment"),
    ("Small intestine cancer",                      "small-intestine-cancer-treatment"),
    ("Tumor biopsy types explained",                "tumor-biopsy-types"),
    ("Smoking and cancer prevention",               "smoking-cancer-prevention"),
    ("Red meat and cancer risk",                    "red-meat-cancer-risk"),
    ("Stress and cancer relationship",              "stress-cancer-link"),
    ("Turmeric and cancer research",                "turmeric-cancer-research"),
    ("Cancer treatment cost India",                 "cancer-treatment-cost-india"),
    ("Ayushman Bharat cancer treatment",            "ayushman-bharat-cancer"),
    ("Cancer screening age guidelines",             "cancer-screening-age-guidelines"),
    ("Tumor mutational burden TMB",                 "tumor-mutational-burden"),
    ("Microsatellite high MSI-H immunotherapy",     "msi-high-immunotherapy"),
    ("Colorectal cancer follow-up schedule",        "colorectal-cancer-followup"),
    ("KRAS wild-type treatment options",            "kras-wildtype-colorectal"),
    ("Stoma care after colorectal surgery",         "stoma-care-colorectal"),
    ("Rectal bleeding when to see doctor",          "rectal-bleeding-cancer-signs"),
    ("Change in bowel habits cancer warning",       "bowel-habits-cancer-signs"),
    ("Iron deficiency anaemia and cancer",          "iron-deficiency-anaemia-cancer"),
],

"dr-imad": [
    ("What is HIPEC surgery",                       "what-is-hipec"),
    ("HIPEC for ovarian cancer",                    "hipec-ovarian-cancer"),
    ("HIPEC for colorectal cancer",                 "hipec-colorectal-cancer"),
    ("HIPEC for gastric cancer",                    "hipec-gastric-cancer"),
    ("PIPAC procedure explained",                   "pipac-procedure-explained"),
    ("PIPAC vs HIPEC comparison",                   "pipac-vs-hipec"),
    ("Cytoreductive surgery CRS explained",         "cytoreductive-surgery-explained"),
    ("PCI score peritoneal cancer index",           "pci-score-peritoneal-cancer"),
    ("Peritoneal metastases treatment",             "peritoneal-metastases-treatment"),
    ("Pseudomyxoma peritonei treatment",            "pseudomyxoma-peritonei"),
    ("Appendix cancer mucinous adenocarcinoma",     "appendix-cancer-mucinous"),
    ("Peritoneal mesothelioma treatment",           "peritoneal-mesothelioma"),
    ("Primary peritoneal cancer",                   "primary-peritoneal-cancer"),
    ("Gastric cancer surgery options",              "gastric-cancer-surgery-options"),
    ("Total gastrectomy for stomach cancer",        "total-gastrectomy-stomach-cancer"),
    ("D2 dissection gastric cancer",                "d2-dissection-gastric-cancer"),
    ("Esophagogastric junction cancer",             "esophagogastric-junction-cancer"),
    ("Whipple procedure patient guide",             "whipple-procedure-guide"),
    ("Whipple surgery recovery diet",               "whipple-recovery-diet"),
    ("Pylorus-preserving Whipple procedure",        "pylorus-preserving-whipple"),
    ("Distal pancreatectomy and splenectomy",       "distal-pancreatectomy-splenectomy"),
    ("Borderline resectable pancreatic cancer",     "borderline-resectable-pancreatic"),
    ("Hepatobiliary cancer surgery Hyderabad",      "hepatobiliary-cancer-hyderabad"),
    ("Right hepatectomy liver cancer",              "right-hepatectomy-liver-cancer"),
    ("Bile duct Klatskin tumour surgery",           "klatskin-tumour-surgery"),
    ("Gallbladder cancer surgery options",          "gallbladder-cancer-surgery-options"),
    ("Radical cholecystectomy gallbladder",         "radical-cholecystectomy"),
    ("GIST treatment and imatinib",                 "gist-treatment-imatinib"),
    ("Retroperitoneal tumour surgery",              "retroperitoneal-tumour-surgery"),
    ("Colorectal liver metastases surgery",         "colorectal-liver-metastases-crs"),
    ("Ovarian cancer surgery and HIPEC",            "ovarian-cancer-hipec"),
    ("BRCA ovarian cancer surgical options",        "brca-ovarian-cancer-surgery"),
    ("Malignant ascites treatment options",         "malignant-ascites-treatment"),
    ("Laparoscopic staging peritoneal cancer",      "laparoscopic-staging"),
    ("Second opinion for HIPEC surgery",            "second-opinion-hipec"),
    ("HIPEC surgery cost India",                    "hipec-cost-india"),
    ("Life after HIPEC surgery",                    "life-after-hipec"),
    ("Recovery after cytoreductive surgery",        "recovery-cytoreductive-surgery"),
    ("Peritoneal cancer can it be operated",        "peritoneal-cancer-surgery-possible"),
    ("When is HIPEC not recommended",               "hipec-contraindications"),
    ("Intraperitoneal chemotherapy explained",      "intraperitoneal-chemotherapy"),
    ("Gastric cancer peritoneal spread",            "gastric-cancer-peritoneal-spread"),
    ("Appendix rupture and cancer risk",            "appendix-rupture-cancer-risk"),
    ("Liver cancer resection margin",               "liver-cancer-resection"),
    ("Portal vein involvement pancreatic cancer",   "portal-vein-pancreatic-cancer"),
    ("GI cancer Hyderabad second opinion",          "gi-cancer-second-opinion-hyderabad"),
    ("Peritoneal cancer survival explained",        "peritoneal-cancer-survival"),
    ("Laparoscopic vs open cancer surgery",         "laparoscopic-vs-open-cancer-surgery"),
    ("CRS HIPEC vs systemic chemotherapy",          "crs-hipec-vs-chemotherapy"),
    ("What cancers can spread to peritoneum",       "cancers-that-spread-to-peritoneum"),
],

}

def load_existing():
    """Load existing rows keyed by (doctor_folder, planned_date)."""
    existing = {}
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                key = (row["doctor_folder"], row["planned_date"])
                existing[key] = row
    return existing

def main():
    existing = load_existing()
    rows = []
    for folder, topics in PLAN.items():
        for i, (topic_en, slug_hint) in enumerate(topics):
            planned_date = (START + timedelta(days=i)).strftime("%Y-%m-%d")
            key = (folder, planned_date)
            if key in existing and existing[key]["status"] == "published":
                rows.append(existing[key])   # preserve published rows as-is
            else:
                rows.append({
                    "doctor_folder": folder,
                    "planned_date":  planned_date,
                    "topic_en":      topic_en,
                    "slug_hint":     slug_hint,
                    "status":        "pending",
                    "built_slug":    "",
                    "built_url":     "",
                    "built_at":      "",
                })

    with open(OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDNAMES)
        w.writeheader()
        w.writerows(rows)

    total = len(rows)
    print(f"Wrote {total} rows to {OUT}")
    for folder in PLAN:
        count = sum(1 for r in rows if r["doctor_folder"] == folder)
        print(f"  {folder}: {count} days planned")

if __name__ == "__main__":
    main()
